version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis/data/:/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_PORT: 5672
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 3s
      retries: 2
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
