version: "3.9"

services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis/data/:/data
  rabbitmq:
    image: rabbitmq:3.12.13-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq
