version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis/data/:/data
    networks:
      - app_network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo/data:/etc/mongo
    networks:
      - app_network

networks:
  app_network:
    external: true
